

### POST request to create a new patient
POST http://localhost:4004/api/patients/create
Content-Type: application/json

{
  "name": "Lomtik",
  "email": "lombada@email.com",
  "address": "Azerbaijan, Baku",
  "dateOfBirth": "2001-11-25",
  "registeredDate": "2025-05-19"
}

###