@basePath=api/v1

### PUT request to update the patient
PUT http://localhost:4000/{{basePath}}/patients/223e4567-e89b-12d3-a456-426614174013/update
Content-Type: application/json

{
  "name": "Ramazan",
  "email": "fghj@example.com",
  "address": "Azerbaijan, Baku",
  "dateOfBirth": "2001-11-25"
}

###